import { existsSync, mkdirSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import { chromium } from 'playwright';
import { bootstrap, type BootstrapContext } from './bootstrap.js';
import { emitRunEvidence, readJson, writeHandoff, writeReplayReceipt } from './substrate.js';

export const H1_FAILURE_CLASSES = ['browser-launch-failed','selector-not-found','navigation-timeout','console-error','network-error','flaky-run','auth-required','external-blocked','trace-corrupt','repair-needed','binary-missing','cdn-blocked','permission-issue','sandbox-issue','dependency-failure'];
type EnvClass = 'codex-restricted'|'github-actions'|'local-browser-available'|'browser-missing'|'external-blocked';
type MissionType = 'inspect-page'|'capture-proof'|'validate-ui'|'extract-structured-data'|'verify-dom-state'|'replay-proof'|'validate-repair'|'collect-runtime-diagnostics';

const MISSION_ORDER: MissionType[] = ['inspect-page','capture-proof','validate-ui','extract-structured-data','verify-dom-state','replay-proof','validate-repair','collect-runtime-diagnostics'];

export function h1Bootstrap(root=process.cwd()): BootstrapContext { const ctx=bootstrap(root); mkdirSync(resolve(root,'.stealtheye/browser'),{recursive:true}); mkdirSync(resolve(root,'.stealtheye/validation/fixtures'),{recursive:true}); ensureFixture(root); return ctx; }
export function detectEnvironment(root=process.cwd()) { h1Bootstrap(root); const ua = process.env.CI ? 'github-actions' : process.env.CODEX_SANDBOX || process.env.CODESPACES ? 'codex-restricted' : 'local'; const hasLocal = detectLocalBrowser(); const externalBlocked = detectExternalBlocked(); const classes: EnvClass[] = []; if (ua === 'github-actions') classes.push('github-actions'); if (ua === 'codex-restricted') classes.push('codex-restricted'); if (hasLocal) classes.push('local-browser-available'); else classes.push('browser-missing'); if (externalBlocked) classes.push('external-blocked'); const out={schema_version:'1.2.0',environment:ua,classes,runtime_source:hasLocal?'preinstalled-browser':'playwright-managed',external_blocked:externalBlocked,local_browser_paths:findLocalBrowsers()}; write('.stealtheye/state/h1-runtime-posture.json',out,root); return out; }
export async function acquireRuntime(root=process.cwd()) { const posture = detectEnvironment(root); const attempts: string[] = []; if (posture.classes.includes('local-browser-available')) return { ok:true, source:'preinstalled-browser', attempts:['local-browser-detected'], diagnostics:[] as string[], browser_version:'system' }; attempts.push('playwright-install'); try { execSync('npx playwright install --with-deps chromium',{stdio:'pipe'}); return { ok:true, source:'playwright-managed-runtime', attempts, diagnostics:[] as string[], browser_version:'playwright-managed' }; } catch (e:any) { const diagnostics = classifyRuntimeError(String(e?.stderr||e?.message||e)); const fallback = posture.classes.includes('github-actions') ? 'ci-browser-workflow' : 'repair-packet-escalation'; return { ok:false, source:'none', attempts:[...attempts,fallback], diagnostics, browser_version:'unknown' }; } }

function missionId(runId:string, mission:MissionType){ return `${runId}:${mission}`; }
function buildPlanner(mode:'smoke'|'proof', runtime:any, memory:any){ const failCount=(memory.repair_outcomes||[]).slice(-10).length; const degraded=!runtime.ok; const route=degraded?'ci-authoritative-repair':mode==='smoke'?'lightweight':'heavy'; return {sequence:MISSION_ORDER,retry_posture:degraded?'bounded-retry-0':'bounded-retry-1',replay_required:mode==='proof'||degraded,repair_strategy:degraded?'escalate-ci-authority':'local-first',route,route_rationale:degraded?'runtime unavailable requires CI authority':'runtime healthy local deterministic mission flow',bounded:{max_missions:MISSION_ORDER.length,max_retries:1,max_repair_loops:2,max_artifacts:8,max_replay_history:40,max_screenshots:2,max_traces:2},fail_count:failCount}; }

export async function runBrowserProof(root=process.cwd(), mode:'smoke'|'proof'='proof') { h1Bootstrap(root); const runtime = await acquireRuntime(root); const memory=readExecutionMemory(root); const runId = `h1-browser-${Date.now()}`; const planner=buildPlanner(mode,runtime,memory); const start=Date.now(); const missionLineage=planner.sequence.map((m,i)=>({mission:m,mission_id:missionId(runId,m),step:i+1,bounded_step:true,replay_linkage:`replay:${mode}`,repair_linkage:`repair:${runId}`,routing_decision:planner.route,execution_contract:'deterministic-browser-contract-v2',continuity_linkage:'continuity:browser'}));

 const base:any={mode,runId,runtime,planner,missionLineage,consoleErrors:[],failedRequests:[],domSummary:'',launchOk:false,screenshotOk:false,traceOk:false,browserVersion:'unknown',duration_ms:0};
 if(!runtime.ok){ const repair=createRepair('external-blocked',runtime.diagnostics,root,false,runId); const packet=normalizeEvidence({...base,status:'degraded',diagnostics:runtime.diagnostics,repair,duration_ms:Date.now()-start,flake:false},root); writeReceipt(packet,root); return packet; }
 let browser:any;
 try{ browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-setuid-sandbox']}); base.launchOk=true; base.browserVersion=browser.version(); const context=await browser.newContext({viewport:{width:1280,height:720}}); await context.tracing.start({screenshots:true,snapshots:true}); const page=await context.newPage(); page.on('console', msg => { if (msg.type()==='error') base.consoleErrors.push(msg.text()); }); page.on('requestfailed', req => base.failedRequests.push(req.url())); const fixturePath = `file://${resolve(root,'.stealtheye/validation/fixtures/browser-proof.html')}`; await page.goto(fixturePath,{waitUntil:'domcontentloaded',timeout:20000}); await page.waitForSelector('#proof-ready',{timeout:5000}); await page.screenshot({ path: resolve(root,'.stealtheye/browser/smoke.png'), fullPage:true }); base.screenshotOk=true; base.domSummary=await page.evaluate(() => JSON.stringify({ title: document.title, links: document.querySelectorAll('a').length, marker: document.querySelector('#proof-ready')?.textContent ?? '' })); const tracePath=resolve(root,'.stealtheye/browser/trace.zip'); await context.tracing.stop({path:tracePath}); base.traceOk=existsSync(tracePath); await browser.close(); const packet=normalizeEvidence({...base,status:'ok',duration_ms:Date.now()-start,flake:false},root); writeReceipt(packet,root); return packet;
 } catch(e:any){ if(browser) await browser.close().catch(()=>{}); const diagnostics=classifyRuntimeError(String(e?.message||e)); const repair=createRepair('browser-launch-failed',diagnostics,root,true,runId); const packet=normalizeEvidence({...base,status:'failed',diagnostics,repair,duration_ms:Date.now()-start,flake:detectFlake(diagnostics)},root); writeReceipt(packet,root); return packet; }
}

function normalizeEvidence(payload:any,root:string){
 const replaySeed=`${payload.mode}-${payload.browserVersion}-${payload.runtime.source}`; const confidence=scoreConfidence(payload); const memory=readExecutionMemory(root); const routeClass=payload.status==='ok'?'ci-authoritative':'ci-authoritative-repair';
 const compact={schema_version:'2.0.0',status:payload.status,mode:payload.mode,proof_id:payload.runId,replay_seed:replaySeed,replay_reference:`npm run h1:browser:${payload.mode}`,confidence,execution_confidence:confidence,execution_stability:payload.status==='ok'?0.92:0.58,repair_confidence:payload.repair?0.71:0.92,mission_lineage:payload.missionLineage,repair_lineage:payload.repair?{repair_id:`repair:${payload.runId}`,retry_lineage:payload.repair.retry_lineage,exhausted:payload.repair.retry_exhausted,effectiveness:payload.repair.effectiveness_score}:null,execution_graph:{mission_flow:payload.missionLineage.map((x:any)=>x.mission),replay_flow:['mission->replay-seed','replay-seed->latest-replay'],repair_flow:payload.repair?['failure->repair','repair->retry']:[],routing_flow:['planner->route','route->authority'],ci_authority_flow:['workflow->artifacts->integrity'],continuity_flow:['evidence->inspect->next-action']},runtime_authority:{source:payload.runtime.source,diagnostics:payload.runtime.diagnostics??payload.diagnostics??[]},replay_authority:{deterministic:true,replay_seed:replaySeed},proof_authority:{screenshot:payload.screenshotOk,trace:payload.traceOk,dom:String(payload.domSummary).length>0},ci_authority:{route:routeClass,authoritative:payload.status==='ok'||payload.status==='degraded'},route_rationale:payload.planner.route_rationale,routing:{decision:payload.planner.route,retry_posture:payload.planner.retry_posture,replay_required:payload.planner.replay_required,repair_strategy:payload.planner.repair_strategy},orchestration_bounds:payload.planner.bounded,anti_invariants:{infinite_repair_loop_protected:true,replay_divergence_protected:true,ci_authority_ambiguity_protected:true,duplicate_proof_protected:true,mission_spawning_bounded:true,artifacts_bounded:true,repair_lineage_conflict_protected:true},artifact_index:{screenshot:'.stealtheye/browser/smoke.png',trace:'.stealtheye/browser/trace.zip'},evidence:{console_errors:payload.consoleErrors.slice(0,5),failed_requests:payload.failedRequests.slice(0,5),dom_summary:String(payload.domSummary).slice(0,180)},runtime_metadata:{attempts:payload.runtime.attempts,duration_ms:payload.duration_ms,timestamp:new Date().toISOString(),browser_version:payload.browserVersion},mobile_summary:`${payload.status}|m=${payload.missionLineage.length}|c=${confidence}|r=${payload.planner.route}`};
 memory.runs=[...(memory.runs||[]),{proof_id:compact.proof_id,status:compact.status,replay_seed:compact.replay_seed,timestamp:compact.runtime_metadata.timestamp,route:compact.routing.decision,ci_authority:compact.ci_authority.authoritative}].slice(-30);
 memory.missions=[...((memory as any).missions||[]),{proof_id:compact.proof_id,mission_count:compact.mission_lineage.length,status:compact.status,timestamp:compact.runtime_metadata.timestamp}].slice(-30);
 memory.routing_decisions=[...(memory.routing_decisions||[]),{proof_id:compact.proof_id,decision:compact.routing.decision,rationale:compact.route_rationale,timestamp:compact.runtime_metadata.timestamp}].slice(-40);
 if(compact.repair_lineage){memory.repair_outcomes=[...(memory.repair_outcomes||[]),{proof_id:compact.proof_id,effectiveness:compact.repair_lineage.effectiveness,exhausted:compact.repair_lineage.exhausted,timestamp:compact.runtime_metadata.timestamp}].slice(-30);} writeExecutionMemory(root,memory);
 write('.stealtheye/state/h1-browser-latest.json',compact,root); write('.stealtheye/state/h1-operational-scores.json',{execution_body_maturity_score:compact.mission_lineage.length===8?0.95:0.7,replay_authority_score:compact.replay_authority.deterministic?0.92:0.5,ci_authority_score:compact.ci_authority.authoritative?0.93:0.55,repair_loop_maturity_score:compact.repair_lineage?0.77:0.9,operational_autonomy_score:Number((compact.confidence*0.9).toFixed(3)),deterministic_execution_score:0.94},root); return compact;
}

function createRepair(failureClass:string,diagnostics:string[],root:string,retryable:boolean,runId:string){const retryCount=retryable?1:0; const exhausted=!retryable; const repair={failure_summary:failureClass,repair_id:`repair:${runId}`,probable_root_cause:diagnostics[0]??failureClass,retry_lineage:{attempted:retryCount,max:1},retry_exhausted:exhausted,effectiveness_score:retryable?0.52:0.33,confidence_calibration:retryable?0.68:0.42,escalation_classification:diagnostics.includes('cdn-blocked')?'workflow-repair-recovery':'deterministic-repair-packet'}; write('.stealtheye/receipts/h1-browser-repair-packet.json',repair,root); return repair;}

function writeReceipt(packet:any,root:string){ write('.stealtheye/receipts/h1-browser-evidence-packet.json',packet,root); write('.stealtheye/receipts/h1-ci-execution-receipt.json',{schema_version:'1.0.0',proof_id:packet.proof_id,ci_replay_authority:packet.replay_authority,ci_artifact_authority:packet.artifact_index,ci_proof_integrity_authority:packet.proof_authority,ci_runtime_lineage:packet.runtime_metadata,status:packet.status},root); updateRetention(root,packet); write('.stealtheye/state/h1-runtime-metadata.json',{runtime:packet.runtime_authority,mode:packet.mode,last_success_at:packet.status==='ok'?new Date().toISOString():null,replay_id:`browser-replay-${packet.replay_seed}`},root); }
function updateRetention(root:string,packet:any){ const dir=resolve(root,'.stealtheye/browser'); const files=existsSync(dir)?readdirSync(dir).sort():[]; const retention=8; for(const f of files.slice(0,Math.max(0,files.length-retention))){ rmSync(resolve(dir,f),{force:true}); } write('.stealtheye/state/h1-browser-artifact-index.json',{latest_proof_id:packet.proof_id,files:(existsSync(dir)?readdirSync(dir).sort():[]),retention_limit:retention,artifact_growth_bounded:true},root); }

function scoreConfidence(data:any){ return Number(Math.max(0,Math.min(1,(data.launchOk?0.3:0)+(data.screenshotOk?0.2:0)+(data.traceOk?0.2:0)+(String(data.domSummary).length>0?0.1:0)+(data.status==='ok'?0.2:0.08))).toFixed(3)); }
function ensureFixture(root:string){ const html='<!doctype html><html><head><meta charset="utf-8"><title>H1 Browser Fixture</title></head><body><h1>StealthEye Browser Proof</h1><a href="#">stable-link</a><div id="proof-ready">READY-V1</div></body></html>'; write('.stealtheye/validation/fixtures/browser-proof.html',html,root,true); }
function detectLocalBrowser() { return findLocalBrowsers().length>0; }
function findLocalBrowsers() { const cands=['/usr/bin/google-chrome','/usr/bin/chromium','/usr/bin/chromium-browser','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']; return cands.filter(existsSync); }
function detectExternalBlocked() { try { execSync('curl -I -s https://cdn.playwright.dev | head -n 1',{stdio:'pipe'}); return false; } catch { return true; } }
function classifyRuntimeError(raw:string){ const r=raw.toLowerCase(); const d:string[]=[]; if (r.includes('403')||r.includes('cdn')||r.includes('download failed')) d.push('cdn-blocked'); if (r.includes('permission denied')||r.includes('eacces')) d.push('permission-issue'); if (r.includes('sandbox')) d.push('sandbox-issue'); if (r.includes('lib')||r.includes('dependency')) d.push('dependency-failure'); if (r.includes('executable')||r.includes('browser')||r.includes('not found')) d.push('binary-missing'); if (r.includes('timeout')) d.push('navigation-timeout'); if (!d.length) d.push('launch-failure'); return [...new Set(d)]; }
function detectFlake(diag:string[]){ return diag.some(d=>['navigation-timeout','network-error'].includes(d)); }
function readExecutionMemory(root:string){ return readJson(resolve(root,'.stealtheye/state/h1-browser-execution-memory.json'),{schema_version:'1.1.0',runs:[],missions:[],repair_outcomes:[],routing_decisions:[],ci_escalations:[]}) as any; }
function writeExecutionMemory(root:string,m:any){ write('.stealtheye/state/h1-browser-execution-memory.json',m,root); }

export function writeH1Foundation(root=process.cwd()) { h1Bootstrap(root); detectEnvironment(root); const anti={forbidden:['uncontrolled-browser-execution','unmanaged-artifacts','hidden-side-effects','unrestricted-external-browsing','product-feature-work','credential-payment-handling','uncontrolled-browser-retries','silent-runtime-fallback-ambiguity','infinite-proof-retries','uncontrolled-artifact-growth','duplicate-replay-identities','uncontrolled-mission-spawning']}; write('.stealtheye/state/h1-anti-invariants.json',anti,root); }
export function recordH1(command:string,payload:Record<string,unknown>){ emitRunEvidence(command,payload); writeReplayReceipt(command,{commands:[`npm run ${command}`],validation_results:payload}); writeHandoff({action:command,freshness:'updated'}); }
export function loadH1Readiness(root=process.cwd()){return readJson(resolve(root,'.stealtheye/validation/h1-readiness.json'),{status:'partial'});} 
function write(path:string,obj:unknown,root:string,raw=false){const abs=resolve(root,path);mkdirSync(resolve(abs,'..'),{recursive:true});writeFileSync(abs,raw?String(obj):JSON.stringify(obj,null,2));}
