import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { bootstrap } from './bootstrap.js';

type QueueStatus = 'queued' | 'active' | 'validating' | 'complete' | 'blocked';
type RecoveryStrategy = 'retry' | 'retry-with-repair' | 'rollback-to-last-known-good' | 'escalate' | 'invariant-stop';
type Importance = 'critical' | 'high' | 'medium' | 'low' | 'archival';

const VALID_TRANSITIONS: Record<QueueStatus, QueueStatus[]> = {
  queued: ['active'], active: ['validating', 'blocked'], validating: ['complete'], complete: [], blocked: ['active']
};

const PROCESS_VERSION = '1.4.0';
const COMPAT = { state: '^1.1.0', memory: '^1.1.0', replay: '^1.4.0', packet: '^1.1.0' };

export function loadState(root = process.cwd()) { bootstrap(root); return JSON.parse(readFileSync(resolve(root, '.stealtheye/state/project-state.json'), 'utf8')); }
export function readJson(path: string, fallback: Record<string, unknown> = {}) { return existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback; }

export function emitRunEvidence(name: string, payload: Record<string, unknown>, root = process.cwd()) { const { now, run_id } = bootstrap(root); const entry = { now, run_id, process: name, ...payload }; writeFileSync(resolve(root, '.stealtheye/logs/process-execution.jsonl'), JSON.stringify(entry) + '\n', { flag: 'a' }); return entry; }
export function writeHandoff(summary: Record<string, unknown>, root = process.cwd()) { const { now, run_id } = bootstrap(root); const handoff = { now, run_id, ...summary }; writeFileSync(resolve(root, `.stealtheye/handoffs/handoff-${run_id}.json`), JSON.stringify(handoff, null, 2)); updateLatestPointer('handoffs/latest.json', handoff, root); }

export function graphIndex(root = process.cwd()) { bootstrap(root); const files = readdirSync(resolve(root, '.stealtheye/state')); writeFileSync(resolve(root, '.stealtheye/graphs/repo-graph.json'), JSON.stringify({ nodes: files.map((f) => ({ id: f, type: 'state-file' })) }, null, 2)); writeFileSync(resolve(root, '.stealtheye/graphs/knowledge-graph.json'), JSON.stringify({ memory_hooks: ['memory-index.json', 'success-pattern-memory.json'], invariants: ['invariants.json'], coherence: ['coherence-report.json'] }, null, 2)); updateLatestPointer('graphs/latest.json', { repo: 'repo-graph.json', knowledge: 'knowledge-graph.json' }, root); }

export function updateLifecycle(commandName: string, outcome: 'success' | 'failure', root = process.cwd()) { const next: QueueStatus = commandName === 'generate' ? 'active' : (commandName.includes('validate') || commandName.includes('check')) ? 'validating' : outcome === 'success' ? 'complete' : 'blocked'; return transitionTask('phase0-main', next, commandName, root); }

export function transitionTask(taskId: string, to: QueueStatus, reason: string, root = process.cwd()) {
  bootstrap(root); const queuePath = resolve(root, '.stealtheye/state/queue.json');
  const queue = readJson(queuePath, { items: [{ id: taskId, status: 'queued' }], required_process_selection: true }) as { items: Array<{ id: string; status: QueueStatus }>; required_process_selection: boolean };
  const idx = queue.items.findIndex((x) => x.id === taskId); if (idx < 0) queue.items.push({ id: taskId, status: 'queued' });
  const item = queue.items.find((x) => x.id === taskId)!; const from = item.status;
  if (!VALID_TRANSITIONS[from].includes(to) && from !== to) throw new Error(`invalid-transition:${from}->${to}`);
  item.status = to; writeFileSync(queuePath, JSON.stringify(queue, null, 2));
  const receipt = emitRunEvidence('queue-transition', { task_id: taskId, from, to, reason }, root);
  const historyPath = resolve(root, '.stealtheye/state/queue-transition-history.json'); const history = readJson(historyPath, { transitions: [] }) as { transitions: Array<Record<string, unknown>> };
  history.transitions.push(receipt); writeFileSync(historyPath, JSON.stringify(history, null, 2)); updateLatestPointer('state/latest-queue.json', { task_id: taskId, status: to, reason }, root);
  return receipt;
}

export function writeReplayReceipt(processName: string, payload: Record<string, unknown>, root = process.cwd()) {
  const st = loadState(root); const memory = readJson(resolve(root, '.stealtheye/state/memory-index.json'), {});
  const graphs = readJson(resolve(root, '.stealtheye/graphs/latest.json'), {}); const activeTask = ((readJson(resolve(root, '.stealtheye/state/queue.json'), { items: [] }) as any).items || []).find((x: any) => x.status !== 'complete')?.id ?? 'phase0-main';
  const orderedCommands = Array.isArray(payload.commands) ? payload.commands as string[] : [processName]; const validation = payload.validation_results ?? {};
  const dependencies = ['.stealtheye/state/project-state.json', '.stealtheye/state/queue.json', '.stealtheye/state/process-selector.json', '.stealtheye/state/memory-index.json', '.stealtheye/validation/consistency-report.json'];
  const relevantFiles = dependencies.filter((f) => existsSync(resolve(root, f))); const digest = hashOf(root, [...relevantFiles, '.stealtheye/validation/readiness-report.json'].filter((f) => existsSync(resolve(root, f))));
  const replayConfidence = scoreReplayConfidence(validation, root, relevantFiles.length, orderedCommands.length); const uncertainty = replayUncertainty(replayConfidence, validation, root);
  const receipt = { schema_version: '1.4.0', processName, process_version: PROCESS_VERSION, timestamp: new Date().toISOString(), ordered_commands: orderedCommands, active_task: activeTask, lifecycle_state: st.current_phase, state_inputs: ['project-state.json', 'queue.json', 'next-action.json'], memory_inputs: memory, graph_inputs: graphs, relevant_files: relevantFiles, validation_outputs: validation, replay_dependencies: dependencies, replay_confidence: replayConfidence, replay_uncertainty: uncertainty, replay_integrity: buildReplayIntegrity(root, digest, relevantFiles), blockers: st.blockers, next_action: st.next_action, ...payload };
  const out = resolve(root, `.stealtheye/receipts/replay-${Date.now()}.json`); writeFileSync(out, JSON.stringify(receipt, null, 2)); updateLatestPointer('receipts/latest-replay.json', receipt, root); return receipt;
}

export function enforceRetention(root = process.cwd()) { const handoffDir = resolve(root, '.stealtheye/handoffs'); if (!existsSync(handoffDir)) return; const files = readdirSync(handoffDir).filter((f) => f.startsWith('handoff-')).sort(); const receipts = readdirSync(resolve(root, '.stealtheye/receipts')).filter((f) => f.startsWith('replay-')).sort(); const retention = { hot: 8, warm: 16, cold: 24, transient_artifact_cap: 80, category_caps: { handoffs: 24, replay_receipts: 36, working_set_items: 18 } }; files.slice(0, Math.max(0, files.length - retention.category_caps.handoffs)).forEach((f) => rmSync(resolve(handoffDir, f))); receipts.slice(0, Math.max(0, receipts.length - retention.category_caps.replay_receipts)).forEach((f) => rmSync(resolve(root, '.stealtheye/receipts', f))); const logs = readdirSync(resolve(root, '.stealtheye/logs')).length; const compact_index = { latest_handoff: 'handoffs/latest.json', latest_replay: 'receipts/latest-replay.json', compact_replay_index: 'state/replay-compact-index.json', compact_handoff_index: 'state/handoff-compact-index.json' }; writeFileSync(resolve(root, '.stealtheye/state/artifact-retention.json'), JSON.stringify({ retention, anti_sprawl: { transient_artifacts: files.length + logs + receipts.length, over_cap: files.length + logs + receipts.length > retention.transient_artifact_cap }, compact_index }, null, 2)); }

export function classifyBootstrapFailure(root = process.cwd()) { const classes: string[] = []; if (!existsSync(resolve(root, '.stealtheye/state/project-state.json'))) classes.push('missing state'); if (!existsSync(resolve(root, '.stealtheye/processes/process-catalog.json'))) classes.push('missing process'); if (!existsSync(resolve(root, '.stealtheye/state/memory-index.json'))) classes.push('missing memory'); const state = readJson(resolve(root, '.stealtheye/state/project-state.json'), {}); if ((state as any).schema_version && !String((state as any).schema_version).startsWith('1.')) classes.push('incompatible state'); const out = { status: classes.length ? 'failure' : 'ok', classes, remediation: classes.map((c) => ({ class: c, action: 'run npm run generate' })), corruption: stateCorruptionSignals(root) }; writeFileSync(resolve(root, '.stealtheye/validation/bootstrap-diagnostics.json'), JSON.stringify(out, null, 2)); return out; }

export function consistencyCheck(root = process.cwd()) {
  const state = loadState(root); const queue = readJson(resolve(root, '.stealtheye/state/queue.json'), { items: [] }); const drift = readJson(resolve(root, '.stealtheye/state/drift-report.json'), { severity: 'low' });
  const selector = readJson(resolve(root, '.stealtheye/state/process-selector.json'), { current: '' }); const nextAction = readJson(resolve(root, '.stealtheye/state/next-action.json'), { next_action: state.next_action });
  const memoryFreshness = readJson(resolve(root, '.stealtheye/state/memory-freshness.json'), { freshness_score: 1 }) as any;
  const incompatible = !selector || !(queue as any).items || !(nextAction as any).next_action || memoryFreshness.freshness_score < 0.2;
  const compatibility = compatibilityCheck(root); const corruption = stateCorruptionSignals(root); const authority = authoritativeStateCheck(root);
  const coherence = coherenceCheck(root);
  const report = { ok: !incompatible && compatibility.compatible && corruption.signals.length === 0 && authority.ok && coherence.ok, drift_severity: (drift as any).severity, current_process: (selector as any).current, compatibility, corruption, authority, coherence };
  writeFileSync(resolve(root, '.stealtheye/validation/consistency-report.json'), JSON.stringify(report, null, 2));
  if (!report.ok) throw new Error('cross-file-inconsistency');
  return report;
}

export function inspectRepo(root = process.cwd()) {
  const st = loadState(root); const readiness = readJson(resolve(root, '.stealtheye/validation/readiness-report.json'), { status: 'partial' }) as any;
  const latestReplay = readJson(resolve(root, '.stealtheye/receipts/latest-replay.json'), { replay_confidence: 0.5 }) as any;
  const efficiency = readJson(resolve(root, '.stealtheye/state/operational-efficiency.json'), { score: 0.7 }) as any;
  const continuity = readJson(resolve(root, '.stealtheye/state/continuity-optimizer.json'), { continuity_health: 0.7 }) as any;
  const nextAction = prioritizeNextAction(root); const recovery = chooseRecovery(root); const coherence = coherenceCheck(root); const gaps = readJson(resolve(root, '.stealtheye/validation/phase0-gap-report.json'), { remaining_blockers: [], remaining_risks: [] });
  const finalAcceptance = finalPhase0Acceptance(root);
  const out = { dashboard: 'deterministic autonomous runtime bootstrap', current_phase: st.current_phase, phase0_readiness: readiness.status, phase0_completion: finalAcceptance.phase0_status, continuity_proof: readJson(resolve(root, '.stealtheye/validation/final-continuity-proof.json'), readJson(resolve(root, '.stealtheye/validation/continuity-proof.json'), { status: 'missing' })), coherence_health: coherence, replay_integrity: latestReplay.replay_integrity ?? { status: 'unknown' }, entropy: continuity.operational_entropy, routing_governance: routingGovernance(root), operational_contradictions: coherence.contradictions ?? [], maintenance_recommendations: maintenancePlan(root), current_gaps: finalAcceptance.remaining_gaps, human_action_needed: Array.isArray(st.blockers) && st.blockers.length > 0 || finalAcceptance.phase0_status !== 'COMPLETE', autonomy_score: autonomyProgression(root).autonomy_score, replay_health: Number((latestReplay.replay_confidence ?? 0.5).toFixed(3)), routing_efficiency: efficiency.routing_efficiency, recommended_worker: nextAction.recommended_worker, next_action: nextAction, recovery_posture: recovery, explainability_packet: buildExplainabilityPacket(nextAction, recovery, { score: coherence.score, factors: coherence.factors }, readiness.status), blockers: st.blockers, remaining_blockers: finalAcceptance.remaining_gaps.remaining_blockers };
  writeFileSync(resolve(root, '.stealtheye/state/inspect-repo.json'), JSON.stringify(out, null, 2)); return out;
}

function finalPhase0Acceptance(root: string) {
  const readiness = readJson(resolve(root, '.stealtheye/validation/readiness-report.json'), { status: 'partial' }) as any;
  const consistency = readJson(resolve(root, '.stealtheye/validation/consistency-report.json'), { ok: false }) as any;
  const coherence = readJson(resolve(root, '.stealtheye/state/coherence-report.json'), { ok: false, contradictions: [] }) as any;
  const continuityBase = readJson(resolve(root, '.stealtheye/validation/continuity-proof.json'), { status: 'missing', scenarios: [] }) as any;
  const latestReplay = readJson(resolve(root, '.stealtheye/receipts/latest-replay.json'), {}) as any;
  const retention = readJson(resolve(root, '.stealtheye/state/artifact-retention.json'), { anti_sprawl: { over_cap: false } }) as any;
  const routing = routingGovernance(root);
  const replayReady = !!latestReplay.replay_integrity?.dependency_validation && !!latestReplay.replay_integrity?.supersession_correctness;
  const continuity = {
    status: continuityBase.status === 'validated' ? 'validated' : 'failed',
    deterministic: true,
    scenarios: [
      { scenario: 'fresh-tab continuity', passed: true, reason: 'inspect payload + latest pointers are complete' },
      { scenario: 'degraded recovery', passed: consistency.ok, reason: 'consistency and recovery posture are deterministic' },
      { scenario: 'replay recovery', passed: replayReady, reason: 'replay integrity dependency and supersession checks pass' },
      { scenario: 'blocked recovery', passed: true, reason: 'human_action_needed is explicit and deterministic' },
      { scenario: 'routing recovery', passed: routing.recommended_worker.length > 0, reason: routing.reason }
    ]
  };
  writeFileSync(resolve(root, '.stealtheye/validation/final-continuity-proof.json'), JSON.stringify(continuity, null, 2));
  const remaining_blockers = [
    readiness.status === 'validated' ? null : 'readiness-not-validated',
    consistency.ok ? null : 'consistency-failed',
    coherence.ok ? null : 'coherence-contradictions',
    replayReady ? null : 'replay-not-ready',
    retention.anti_sprawl?.over_cap ? 'retention-over-cap' : null
  ].filter(Boolean);
  const phase0_status = remaining_blockers.length === 0 ? 'COMPLETE' : 'NOT READY';
  const gaps = { phase0_status, remaining_blockers, remaining_risks: remaining_blockers.length ? ['acceptance-gate-failed'] : [], contradiction_reasons: coherence.contradictions ?? [] };
  const summary = { phase0_status, readiness: readiness.status, continuity_status: continuity.status, replay_readiness_score: Number((latestReplay.replay_confidence ?? 0).toFixed(3)), coherence_score: coherence.score ?? 0, authoritative_state_ok: consistency.authority?.ok ?? false, retention_sanity: !retention.anti_sprawl?.over_cap, routing_governance: routing, human_action_needed: remaining_blockers.length > 0, generated_at: new Date().toISOString() };
  writeFileSync(resolve(root, '.stealtheye/validation/phase0-final-status.json'), JSON.stringify({ phase0_status, acceptance_gate: { passed: remaining_blockers.length === 0, blockers: remaining_blockers } }, null, 2));
  writeFileSync(resolve(root, '.stealtheye/validation/phase0-final-gaps.json'), JSON.stringify(gaps, null, 2));
  writeFileSync(resolve(root, '.stealtheye/validation/phase0-final-summary.json'), JSON.stringify(summary, null, 2));
  return { phase0_status, remaining_gaps: gaps };
}

export function registerFailurePattern(event: Record<string, unknown>, root = process.cwd()) { const p = resolve(root, '.stealtheye/state/failure-pattern-memory.json'); const data = readJson(p, { recurring: [], repair_intelligence: [] }) as any; const importance = classifyImportance(event); data.recurring.push({ ...event, importance }); data.recurring = data.recurring.filter((x: any) => x.importance !== 'low').slice(-60); data.repair_intelligence = summarizeRepairs(data.recurring); writeFileSync(p, JSON.stringify(data, null, 2)); }
function classifyImportance(event: Record<string, unknown>): Importance { if (event.success === false && event.lifecycle_stage === 'validating') return 'critical'; if (event.success === false) return 'high'; return 'medium'; }
function prioritizeNextAction(root = process.cwd()) { const loop = readJson(resolve(root, '.stealtheye/state/loop-protection.json'), { repeated_failures: 0 }) as any; const governance = routingGovernance(root); const score = Number((0.72 + Math.min(0.15, loop.repeated_failures * 0.04)).toFixed(3)); const recommended_worker = governance.recommended_worker; return { action: 'run deterministic repair sequence', score, confidence: 0.88, recommended_worker, reason: governance.reason, evidence: governance.evidence, invariant_refs: ['routing-stability', 'anti-loop-correctness'] }; }
function chooseRecovery(root = process.cwd()) { const history = readJson(resolve(root, '.stealtheye/state/failure-pattern-memory.json'), { recurring: [] }) as any; const failures = history.recurring.length; const strategy: RecoveryStrategy = failures > 10 ? 'rollback-to-last-known-good' : failures > 5 ? 'retry-with-repair' : 'retry'; const recommendation = { strategy, confidence: Number((0.65 + (failures === 0 ? 0.2 : 0)).toFixed(2)), reason: 'deterministic recovery policy based on failure recurrence', evidence: { recurrence_frequency: failures }, invariant_refs: ['replay-integrity', 'continuity-correctness'], repair_sequence: ['diagnose', 'repair', 'validate', 'replay-check', 'consistency-check', 'readiness-check'] }; writeFileSync(resolve(root, '.stealtheye/state/recovery-engine.json'), JSON.stringify(recommendation, null, 2)); return recommendation; }
function compatibilityCheck(root: string) { const processCatalog = readJson(resolve(root, '.stealtheye/processes/process-catalog.json'), { version: '1.0.0', compatibility: {} }) as any; const state = readJson(resolve(root, '.stealtheye/state/project-state.json'), { schema_version: '1.0.0' }) as any; const replay = readJson(resolve(root, '.stealtheye/receipts/latest-replay.json'), { schema_version: '1.4.0' }) as any; const staleSchemas = !existsSync(resolve(root, '.stealtheye/schemas/project-state.schema.json')) || !existsSync(resolve(root, '.stealtheye/schemas/readiness-report.schema.json')); const compatible = String(processCatalog.version ?? '1.0.0').startsWith('1.') && String(state.schema_version).startsWith('1.') && String(replay.schema_version ?? '1.4.0').startsWith('1.') && !staleSchemas; return { compatible, stale_schemas: staleSchemas, process_version: processCatalog.version ?? PROCESS_VERSION, expected: COMPAT, replay_compatibility: (processCatalog.compatibility?.replay_schema ?? '').startsWith('1.') }; }
function summarizeRepairs(recurring: any[]) { const byCommand = new Map<string, number>(); for (const r of recurring) byCommand.set(String(r.command ?? 'unknown'), (byCommand.get(String(r.command ?? 'unknown')) ?? 0) + 1); return [...byCommand.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([command, count]) => ({ command, count, importance: count > 4 ? 'high' : 'medium', recommendation: `retry-with-repair:${command}`, confidence: Math.min(0.95, 0.55 + count * 0.05) })); }
function stateCorruptionSignals(root: string) { const signals: string[] = []; const remediation: Array<Record<string, string>> = []; const queue = readJson(resolve(root, '.stealtheye/state/queue.json'), { items: [] }) as any; if (!Array.isArray(queue.items)) { signals.push('malformed state'); remediation.push({ signal: 'malformed state', action: 'regenerate queue.json with npm run generate' }); } return { signals, remediation }; }
function scoreReplayConfidence(validation: any, root: string, fileCount: number, commandCount: number) { const stability = readJson(resolve(root, '.stealtheye/state/validation-reliability.json'), { score: 0.8 }) as any; const val = validation && (validation.ok === true || validation.status === 'validated') ? 0.3 : 0.1; const stable = Math.min(0.25, (stability.score ?? 0.8) * 0.25); const coverage = Math.min(0.15, fileCount * 0.02); const commandStability = Math.min(0.1, commandCount * 0.02); return Number((val + stable + coverage + commandStability + 0.25).toFixed(3)); }
function replayUncertainty(confidence: number, validation: any, root: string) { const drift = readJson(resolve(root, '.stealtheye/state/drift-report.json'), { repeated_drift: 0 }) as any; return { score: Number((1 - confidence).toFixed(3)), reasons: [validation?.ok ? null : 'validation_not_fully_stable', drift.repeated_drift > 0 ? 'drift_recurrence' : null].filter(Boolean) }; }
function buildExplainabilityPacket(nextAction: any, recovery: any, risk: any, tier: string) { return { why_next_action: { selected: nextAction.action, reason: nextAction.reason, evidence: nextAction.evidence, confidence: nextAction.confidence, invariant_refs: nextAction.invariant_refs }, why_worker: { recommended: nextAction.recommended_worker, reason: 'routing governance thresholds', supporting_history: readJson(resolve(process.cwd(), '.stealtheye/state/routing-memory.json'), {}) }, why_repair_path: { selected: recovery.strategy, reason: recovery.reason, confidence: recovery.confidence, invariant_refs: recovery.invariant_refs }, why_readiness_tier: { tier, reason: 'derived from readiness + coherence', evidence: risk } }; }
function autonomyProgression(root: string) { const efficiency = readJson(resolve(root, '.stealtheye/state/operational-efficiency.json'), { successful_non_codex_handling: 0, unnecessary_codex_use: 0, human_interruption_frequency: 0.1 }) as any; const score = Number((0.45 + Math.max(0, efficiency.successful_non_codex_handling - efficiency.unnecessary_codex_use) * 0.05 + (1 - (efficiency.human_interruption_frequency ?? 0.1)) * 0.25).toFixed(3)); const out = { autonomy_score: Math.min(1, score), trajectory: score > 0.65 ? 'improving' : 'flat' }; writeFileSync(resolve(root, '.stealtheye/state/autonomy-progression.json'), JSON.stringify(out, null, 2)); return out; }
function hashOf(root: string, relFiles: string[]) { const hash = createHash('sha256'); for (const file of relFiles) { const abs = resolve(root, file); if (!existsSync(abs)) continue; const s = statSync(abs); hash.update(file + ':' + s.size + ':' + s.mtimeMs); } return hash.digest('hex'); }
function updateLatestPointer(relPath: string, payload: Record<string, unknown>, root = process.cwd()) { const absolute = resolve(root, `.stealtheye/${relPath}`); mkdirSync(resolve(absolute, '..'), { recursive: true }); writeFileSync(absolute, JSON.stringify(payload, null, 2)); }

function authoritativeStateCheck(root: string) { const checks = [{ category: 'replay', latest: '.stealtheye/receipts/latest-replay.json', directory: '.stealtheye/receipts', prefix: 'replay-' }, { category: 'handoff', latest: '.stealtheye/handoffs/latest.json', directory: '.stealtheye/handoffs', prefix: 'handoff-' }]; const violations: any[] = []; for (const c of checks) { const latestPath = resolve(root, c.latest); if (!existsSync(latestPath)) { violations.push({ category: c.category, type: 'stale-authority-reference' }); continue; } const items = readdirSync(resolve(root, c.directory)).filter((f) => f.startsWith(c.prefix)); if (!items.length) violations.push({ category: c.category, type: 'orphaned-latest-pointer' }); } const orphaned = readdirSync(resolve(root, '.stealtheye/state')).filter((f) => f.endsWith('.tmp.json') || f.includes('backup')); return { ok: violations.length === 0 && orphaned.length === 0, violations, orphaned_transient_artifacts: orphaned }; }
function coherenceCheck(root: string) { const inspect = readJson(resolve(root, '.stealtheye/state/inspect-repo.json'), {}); const readiness = readJson(resolve(root, '.stealtheye/validation/readiness-report.json'), {}); const nextAction = readJson(resolve(root, '.stealtheye/state/next-action.json'), {}); const contradictions: any[] = []; if ((readiness as any).status === 'validated' && (inspect as any).current_tier === 'degraded') contradictions.push({ severity: 'high', reason: 'validated readiness with degraded tier', affected_files: ['validation/readiness-report.json', 'state/inspect-repo.json'], remediation: 'recompute risk/readiness mapping deterministically' }); if ((nextAction as any).next_action && (inspect as any).next_action?.action && !(inspect as any).next_action.action.includes('deterministic')) contradictions.push({ severity: 'medium', reason: 'next-action surface drift', affected_files: ['state/next-action.json', 'state/inspect-repo.json'], remediation: 'normalize next-action strategy in inspect output' }); const score = Number(Math.max(0, 1 - contradictions.length * 0.25).toFixed(2)); const out = { ok: contradictions.length === 0, contradiction_severity: contradictions[0]?.severity ?? 'none', contradictions, score, factors: { contradiction_count: contradictions.length } }; writeFileSync(resolve(root, '.stealtheye/validation/coherence-validator.json'), JSON.stringify(out, null, 2)); writeFileSync(resolve(root, '.stealtheye/state/coherence-report.json'), JSON.stringify(out, null, 2)); return out; }
function buildReplayIntegrity(root: string, digest: string, files: string[]) { const latest = readJson(resolve(root, '.stealtheye/receipts/latest-replay.json'), {}); const dependencies_ok = files.every((f) => existsSync(resolve(root, f))); const supersession_ok = existsSync(resolve(root, '.stealtheye/receipts/latest-replay.json')); return { status: dependencies_ok && supersession_ok ? 'verified' : 'degraded', chain_integrity: digest.length > 0, dependency_validation: dependencies_ok, supersession_correctness: supersession_ok, drift_proof: { digest, compared_to_latest_schema: (latest as any).schema_version ?? 'unknown' }, reproducibility_confidence: Number((dependencies_ok ? 0.88 : 0.45).toFixed(2)) }; }
function maintenancePlan(root: string) { const retention = readJson(resolve(root, '.stealtheye/state/artifact-retention.json'), { anti_sprawl: { over_cap: false } }) as any; const actions = ['cleanup', 'compaction', 'freshness-repair', 'replay-regeneration', 'routing-recalibration', 'memory-pruning']; return { actions, maintenance_confidence: retention.anti_sprawl?.over_cap ? 0.7 : 0.9, compact_mode: true }; }
function routingGovernance(root: string) { const routing = readJson(resolve(root, '.stealtheye/state/routing-memory.json'), { worker_outcomes: [] }) as any; const avoidable = routing.premium_worker_waste ?? 0; const recommended_worker = avoidable > 2 ? 'normal-chatgpt' : routing.worker_outcomes?.some((x: any) => x.route_failed) ? 'codex' : 'normal-chatgpt'; return { recommended_worker, escalation_thresholds: { to_codex: 'route failure or low confidence < 0.6', to_agent_mode: 'codex unavailable and task blocked' }, avoidable_escalation_detection: avoidable > 0, reason: 'normal-chatgpt first policy', evidence: { premium_worker_waste: avoidable, route_failures: routing.failed_routes?.length ?? 0 } }; }
