import { inspectRepo, readJson } from '../lib/substrate.js';
import { detectEnvironment, recordH1, writeH1Foundation, loadH1Readiness } from '../lib/h1.js';
writeH1Foundation();
const base=inspectRepo();
const h1=loadH1Readiness() as any;
const posture=detectEnvironment();
const evidence=readJson('.stealtheye/state/h1-browser-latest.json',{}) as any;
const memory=readJson('.stealtheye/state/h1-browser-execution-memory.json',{runs:[],repair_outcomes:[],missions:[]}) as any;
const scores=readJson('.stealtheye/state/h1-operational-scores.json',{}) as any;
const out={...base,h1_readiness:h1.status,execution_control_dashboard:{mission_status_dashboard:{latest_proof:evidence.proof_id??null,mission_count:evidence.mission_lineage?.length??0,status:evidence.status??'pending'},operational_routing_dashboard:evidence.routing??{},repair_dashboard:evidence.repair_lineage??null,ci_authority_dashboard:evidence.ci_authority??{},replay_dashboard:evidence.replay_authority??{},execution_memory_dashboard:{runs:(memory.runs||[]).length,missions:(memory.missions||[]).length,repairs:(memory.repair_outcomes||[]).length},scores,mobile_summary:evidence.mobile_summary??'pending'},operational_posture:{autonomy_score:scores.operational_autonomy_score??0.5,readiness:h1.status,routing:evidence.routing?.decision??'pending',recovery:evidence.repair_lineage?.exhausted?'escalated':'stable'}};
console.log(JSON.stringify(out,null,2));
recordH1('h1:inspect',{status:'ok',operational:true} as any);
