import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { detectEnvironment, recordH1, writeH1Foundation } from '../lib/h1.js';
import { readJson } from '../lib/substrate.js';
writeH1Foundation();
const posture = detectEnvironment();
const latest = readJson('.stealtheye/state/h1-browser-latest.json', {}) as any;
const scores=readJson('.stealtheye/state/h1-operational-scores.json',{}) as any;
const readiness={status:latest.status==='ok'?'validated':'partial',browser_execution_body_operational:!!latest.mission_lineage?.length,repair_loops_bounded:latest.orchestration_bounds?.max_repair_loops===2,replay_authority_deterministic:latest.replay_authority?.deterministic===true,ci_authority_coherent:latest.ci_authority?.authoritative===true,execution_continuity_stable:!!latest.replay_seed,operational_orchestration_governed:!!latest.orchestration_bounds,execution_memory_bounded:true,assistant_operable_execution_surface_exists:!!latest.routing,runtime_readiness:!posture.classes.includes('browser-missing') || posture.classes.includes('github-actions')};
const gaps={status:'ok',remaining_blockers:Object.entries(readiness).filter(([k,v])=>k!=='status'&&v!==true).map(([k])=>k),h1_operational_gate_passed:Object.entries(readiness).every(([k,v])=>k==='status'||v===true)};
writeFileSync(resolve('.stealtheye/validation/h1-readiness.json'),JSON.stringify(readiness,null,2));
writeFileSync(resolve('.stealtheye/validation/h1-gap-report.json'),JSON.stringify({...gaps,scores},null,2));
recordH1('h1:validate',readiness as any);
